name: Deploy

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
 deploy:
    runs-on: self-hosted
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 3.11.2

       - name: Run echo
        run: |
           echo "hello world!"
                  
     
