name: Deploy

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  deploy-test:

    runs-on: [ self-hosted, runners-test ]
    environment: testing

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 3.11.2

       - name: Helm upgrade/install release
        run: |
           echo "hello world!"
                  
     
